import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { CanonicalizationError, canonicalJson, compareCodePoints, deterministicCalculationHash } from './calculation-run-hashing';

/**
 * Cross-language canonical hash parity (Part B §B5).
 *
 * The fixture file is generated by REAL Python Workbench executions and runs
 * unchanged through the Python suite (tests/test_workbench.py
 * CrossLanguageFixtureTest) and this TypeScript suite. Every hash must match
 * exactly — a calculation run whose hashes cannot be independently reproduced
 * is not accepted.
 */

interface HashFixtureCase {
  name: string;
  calculator_id: string;
  calculator_version: string;
  formula_version: string;
  status: string;
  input_manifest: Record<string, unknown>;
  expected_input_hash: string;
  result_envelope: Record<string, unknown>;
  expected_result_hash: string;
}

const FIXTURE_PATH = path.resolve(__dirname, '../../../../../../packages/contracts/fixtures/financial-calculation-hash-fixtures.v1.json');

describe('cross-language canonical calculation hashing', () => {
  const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as { fixture_version: number; cases: HashFixtureCase[] };

  it('loads the versioned fixture file with the expected coverage', () => {
    expect(fixture.fixture_version).toBe(1);
    expect(fixture.cases.length).toBeGreaterThanOrEqual(6);
    const statuses = new Set(fixture.cases.map((c) => c.status));
    expect(statuses).toContain('completed');
    expect(statuses).toContain('insufficient_information');
    expect(statuses).toContain('invalid_input');
  });

  for (const kind of ['input', 'result'] as const) {
    it(`reproduces every Python-computed ${kind} hash exactly`, () => {
      for (const testCase of fixture.cases) {
        const binding = {
          calculator_id: testCase.calculator_id,
          calculator_version: testCase.calculator_version,
          formula_version: testCase.formula_version
        };
        const manifest = kind === 'input' ? testCase.input_manifest : testCase.result_envelope;
        const expected = kind === 'input' ? testCase.expected_input_hash : testCase.expected_result_hash;
        expect(deterministicCalculationHash(manifest, binding), testCase.name).toBe(expected);
      }
    });
  }

  it('escapes non-ASCII exactly like Python ensure_ascii (incl. surrogate pairs)', () => {
    expect(canonicalJson('transitário — ✓')).toBe('"transit\\u00e1rio \\u2014 \\u2713"');
    // Supplementary plane: 🚢 U+1F6A2 → surrogate pair 🚢
    expect(canonicalJson('🚢')).toBe('"\\ud83d\\udea2"');
  });

  it('sorts object keys by code point and keeps null vs missing distinct', () => {
    expect(canonicalJson({ b: 1, a: null })).toBe('{"a":null,"b":1}');
    expect(canonicalJson({ a: null })).not.toBe(canonicalJson({}));
    expect(compareCodePoints('a', 'b')).toBeLessThan(0);
  });

  it('rejects raw floats, undefined, and non-finite numbers as non-canonical', () => {
    expect(() => canonicalJson(1.5)).toThrow(CanonicalizationError);
    expect(() => canonicalJson({ x: undefined })).toThrow(CanonicalizationError);
    expect(() => canonicalJson(Number.NaN)).toThrow(CanonicalizationError);
    // Tagged forms are the canonical representation for those values.
    expect(canonicalJson({ $dec: '1.50' })).toBe('{"$dec":"1.50"}');
  });
});
